GET http://foresight-team09.herokuapp.com/transporter/6/op_transport
###
GET http://foresight-team09.herokuapp.com/transporter/8
###
GET http://foresight-team09.herokuapp.com/demandes
###
GET http://foresight-team09.herokuapp.com/transporter/6/op_transport/state/r
###
GET http://foresight-team09.herokuapp.com/operateurs
###
GET http://foresight-team09.herokuapp.com/operateurs/by-email/bnk@cnas.dz
###
GET http://foresight-team09.herokuapp.com/operateurs/3/transporters
###
GET http://foresight-team09.herokuapp.com/assures/
###
GET http://foresight-team09.herokuapp.com/assures/10/info
###
GET http://foresight-team09.herokuapp.com/reclamations-assure
###
GET http://foresight-team09.herokuapp.com/reclamations-assure/assure/7
###
GET http://foresight-team09.herokuapp.com/reclamations-assure/reclamation/1
###
POST http://foresight-team09.herokuapp.com/reclamations-assure
content-type: application/json

{
    "id_assure":"7",
    "sujet":"Froid",
    "details":"Pas de chauffage",
    "id_op":"2"
}
###
POST http://foresight-team09.herokuapp.com/op_transport
content-type: application/json

{
    "kilometrage_attendu":"127",
    "transporteur_id":"7",
    "assure_id":"3",
    "vehicule_id":"2"
}

###
POST http://foresight-team09.herokuapp.com/transporter
Content-type: application/json

{
    "nom":"Belmont",
    "prenom":"Richter",
    "operateur_id":"2"

}
###
POST http://foresight-team09.herokuapp.com/demande
Content-Type: application/json

{
    "date_demande":"2022-03-27",
    "operateur_id":"2",
    "assure_id":"8"
}
###
PUT http://foresight-team09.herokuapp.com/demandes/2/state/t
###
POST http://foresight-team09.herokuapp.com/assures
Content-Type: application/json

{
    "nom":"This user means",
    "prenom":"Deploiement sucess",
    "date_naiss":"1969-06-09",
    "num_ss":"006666942069"
}

###
GET http://foresight-team09.herokuapp.com/reclamations-assure/state/ec
###
GET http://foresight-team09.herokuapp.com/reclamations-assure/stats/state
###
GET http://foresight-team09.herokuapp.com/operateurs/2/op_transport
###
GET http://foresight-team09.herokuapp.com/operateurs/2/op_transport/stats/state
###
GET  http://foresight-team09.herokuapp.com/op_transport/stats/state
###
GET http://foresight-team09.herokuapp.com/agent-cnas
###
GET http://foresight-team09.herokuapp.com/agent-cnas/2
###
GET http://foresight-team09.herokuapp.com/agent-cnas/by-email/007bond@cnas.dz
###
POST http://foresight-team09.herokuapp.com/operateurs
Content-Type: application/json

{
    "adresse_operateur":"Reghaia",
    "nom_operateur":"Reghaia15",
    "email_operateur":"regh@cnas.dz",
    "pwd_operateur":"0000"
}
###
GET http://foresight-team09.herokuapp.com/op_transport/13/refund
###
GET http://foresight-team09.herokuapp.com/reclamations-operateur/3
###
POST http://foresight-team09.herokuapp.com/reclamations-operateur
Content-Type: application/json
{
    "operateur_id":"4",
    "assure_id":"5",
    "sujet":"Sujet Sujet de Reclamation",
    "details":"Detail Details de reclamation"
}